GPUS: "0"
WORKERS: 2
OUTPUT: "outputs"
SAVE_ALL_EPOCHES: true  # false - only saves the last epoch, true - saves all

CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

DATASET: 
  NAME: "customds"
  TRAIN:  "/mnt/hdd10tb/Users/phonghh/data/mnist/train"  
  VAL:  "/mnt/hdd10tb/Users/phonghh/data/mnist/test"  
  CLS: "0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
  NUM_CLS: 10 
  IMG_EXT:
  - jpg
  - jpeg
  - png
  FLIP: false 
  GRAYSCALE:
  COLORJITTER:
  GAUSSIAN_BLUR:
    PROB: 0.05
    KERNEL_SIZE: 
    - 5 
    - 9
    SIGMA: 
    - 0.1
    - 5.0
  PERSPECTIVE:
    PROB: 0.1
    SCALE: 0.6
  ROTATE: 
    DEGREES: 
    - -20 
    - 20
    PROB: 0.2
  RANDOM_CROP: 
  RANDOM_ERASING:
  OVERSAMPLING: false
  GRAY: true 

MODEL:
  BACKBONE: 
    NAME: "simple_cnn"
    WIDEN_FACTOR: '1.0x'  # '1.0x'
  NECK: "GlobalAveragePooling"
  HEAD:
    NAME: "LinearCls"
    DROPOUT: 0.2
    LOSS: "CrossEntropy"
    LOSS_WEIGHT:
  INPUT_SHAPE: 
  - 28 
  - 28 
  FREEZE: ""  # backbone, neck or head; separated by ','; exp: "backbone, neck"

TRAIN:
  AUTO_RESUME: true
  CKPT: 
  PRETRAINED:   
  EPOCHS: 10
  EARLY_STOPPING:
  LR_SCHEDULE: "multistep"
  WARMUP:
  WARMUP_FREEZE:
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 6 
  - 8 
  BATCH_SIZE: 16 
  OPTIMIZER: "adam"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.001
  SHUFFLE: true

TEST:
  BATCH_SIZE: 16 
  WEIGHTS: 'weights/mnist_simple_cnn_none_linearcls_100eps.pth'
  METRIC: 'acc'
  SHUFFLE: true
